### ISSUE TITLE
Need 10 questions for Chapter #10 in questionBank.txt

### ISSUE THREAD

**Issue by IncludeKyle** [IncludeKyle/JavaQuizFinal#1]
The program uses a text file questionBank.txt.
There are to be at least 10 questions from each of the 10 general categories, or 100+ questions overall.  Questions can be T/F, multiple choice, and short answer (one word or number).  
There should be an approximate balance between these question types.
Each question should be structure to account for the following:
Question :: Answer :: Category :: Sub-Topic  
File questionBank.txt should include the following columns: 
- Subject
- Category (or textbook section or chapter) of the question or exercise
- The correct answer

**Comment by bjumbeck** [comment]
Have the questions for Chapter #10 done, they are on my work computer so will have them uploaded to master tonight.

**Comment by bjumbeck** [comment]
Completed with #26
